esphome:
  name: NODE_NAME
  platform: ESP8266
  board: esp12e

# Enable logging
logger:

ota:
  password: "PASSWORD"

wifi:
  ssid: "WIFI_NAME"
  password: "PASSWORD"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
  domain: ".fritz.box"

captive_portal:

mqtt:
  broker: raspberrypi4
  on_message:
    - topic: NODE_NAME/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: NODE_NAME/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1
        
sensor:
  - platform: dht
    model: DHT22
    pin: GPIO12
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 4s

deep_sleep:
  run_duration: 5s
  sleep_duration: 10min
  id: deep_sleep_1
